apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: gitea
  namespace: gitea
spec:
  host: gitea.gitea.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 100
        maxRequestsPerConnection: 1000
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 10s
      baseEjectionTime: 30s
