apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: gitea-http
  namespace: gitea
spec:
  host: gitea-http.gitea.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
