apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: gitea-gw
  namespace: gitea
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - git.asnk.io

    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: gitea-tls
      hosts:
        - git.asnk.io

    - port:
        number: 22
        name: ssh
        protocol: TCP
      hosts:
        - git.asnk.io
