apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gitea-network-policy
  namespace: gitea
spec:
  podSelector: {}
  policyTypes: ["Ingress", "Egress"]

  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: gitea

    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system

  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - { protocol: UDP, port: 53 }
        - { protocol: TCP, port: 53 }

    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system
      ports:
        - { protocol: TCP, port: 15008 }

    - to:
        - ipBlock: { cidr: "0.0.0.0/0" }
        - ipBlock: { cidr: "::/0" }
      ports:
        - { protocol: TCP, port: 80 }
        - { protocol: TCP, port: 443 }
        - { protocol: TCP, port: 22 }
        - { protocol: TCP, port: 587 }
        - { protocol: UDP, port: 53 }
        - { protocol: TCP, port: 53 }
