apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gitea-network-policy
  namespace: gitea
spec:
  podSelector: {}
  policyTypes: ["Egress"]
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
