apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: s3-external
  namespace: gitea
spec:
  hosts:
    - fsn1.your-objectstorage.com
  location: MESH_EXTERNAL
  resolution: DNS
  ports:
    - number: 443
      name: tls
      protocol: TLS
