apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: gitea
  namespace: gitea
spec:
  hosts:
    - git.asnk.io
  gateways:
    - gitea-gateway

  http:
    - match:
        - port: 80
          uri:
            prefix: /.well-known/acme-challenge/
      route:
        - destination:
            host: gitea.gitea.svc.cluster.local
            port:
              number: 3000

    - match:
        - port: 80
      redirect:
        scheme: https
        port: 443
        redirectCode: 308

    - match:
        - port: 443
          uri:
            prefix: /
      route:
        - destination:
            host: gitea.gitea.svc.cluster.local
            port:
              number: 3000
