apiVersion: v1
kind: Service
metadata:
  name: lgtm-stack-service
  namespace: lgtm-stack
spec:
  selector:
    app: lgtm-stack
  ports:
    - name: grafana
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: pyroscope
      protocol: TCP
      port: 4040
      targetPort: 4040
    - name: otel-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: otel-http
      protocol: TCP
      port: 4318
      targetPort: 4318
    - name: prometheus
      protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lgtm-stack
  namespace: lgtm-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lgtm
  template:
    metadata:
      labels:
        app: lgtm
    spec:
      containers:
        - name: lgtm
          image: grafana/otel-lgtm:latest
          ports:
            - containerPort: 3000
            - containerPort: 4040
            - containerPort: 4317
            - containerPort: 4318
            - containerPort: 9090
          readinessProbe:
            exec:
              command:
                - cat
                - /tmp/ready
          volumeMounts:
            - name: tempo-data
              mountPath: /data/tempo
            - name: grafana-data
              mountPath: /data/grafana
            - name: loki-data
              mountPath: /data/loki
            - name: loki-storage
              mountPath: /loki
            - name: p8s-storage
              mountPath: /data/prometheus
            - name: pyroscope-storage
              mountPath: /data/pyroscope
      volumes:
        - name: tempo-data
          persistentVolumeClaim:
            claimName: lgtm-stack-tempo-data
        - name: loki-data
          persistentVolumeClaim:
            claimName: lgtm-stack-loki-data
        - name: grafana-data
          persistentVolumeClaim:
            claimName: lgtm-stack-grafana-data
        - name: loki-storage
          persistentVolumeClaim:
            claimName: lgtm-stack-loki-storage
        - name: p8s-storage
          persistentVolumeClaim:
            claimName: lgtm-stack-p8s-storage
        - name: pyroscope-storage
          persistentVolumeClaim:
            claimName: lgtm-stack-pyroscope-storage
