apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitea-valkey-cluster
  namespace: gitea
spec:
  volumeClaimTemplates:
    - metadata:
        name: valkey-data
        labels:
          app.kubernetes.io/instance: gitea
          app.kubernetes.io/name: valkey-cluster
