apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitea-valkey-cluster
  namespace: gitea
spec:
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        labels:
          app.kubernetes.io/instance: gitea
          app.kubernetes.io/name: valkey-cluster
        name: valkey-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: hcloud-volumes
        resources:
          requests:
            storage: 8Gi
        volumeMode: Filesystem
