apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitea-valkey-cluster
  namespace: gitea
spec:
  volumeClaimTemplates:
    - metadata:
        name: valkey-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: hcloud-volumes
        resources:
          requests:
            storage: 8Gi
