apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: ayame
spec:
  hosts:
    - ssh:
        address: 49.12.109.204
        user: root
        port: 22
        keyPath: ./secrets/ayame-cluster.key
      role: controller
    - ssh:
        address: 91.98.88.234
        user: root
        port: 22
        keyPath: ./secrets/ayame-cluster.key
      role: controller
    - ssh:
        address: 91.99.180.215
        user: root
        port: 22
        keyPath: ./secrets/ayame-cluster.key
      role: controller
    - ssh:
        address: 49.13.208.38
        user: root
        port: 22
        keyPath: ./secrets/ayame-cluster.key
      role: worker
    - ssh:
        address: 91.99.114.110
        user: root
        port: 22
        keyPath: ./secrets/ayame-cluster.key
      role: worker
    - ssh:
        address: 78.46.201.182
        user: root
        port: 22
        keyPath: ./secrets/ayame-cluster.key
      role: worker
    - ssh:
        address: 91.98.83.88
        user: root
        port: 22
        keyPath: ./secrets/ayame-cluster.key
      role: worker
  options:
    wait:
      enabled: true
    drain:
      enabled: true
      force: true
      ignoreDaemonSets: true

---
apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
metadata:
  name: k0s
spec:
  api:
    externalAddress: 10.0.0.3
    k0sApiPort: 9443
    port: 6443
    sans:
      - 10.0.0.3
      - 49.12.16.138
      - 10.0.0.2
      - 138.199.132.121
      - 10.0.0.11
      - 10.0.0.12
      - 10.0.0.13
  extensions:
    helm:
      concurrencyLevel: 5
      repositories:
        - name: cilium
          url: https://helm.cilium.io/
      charts:
        - name: cilium
          chartname: cilium/cilium
          version: "1.16.1"
          namespace: kube-system
          values: |
            kubeProxyReplacement: "true"
            k8sServiceHost: "10.0.0.3"
            k8sServicePort: "6443"
            tunnelProtocol: ""
            routingMode: "native"
            autoDirectNodeRoutes: true
            ipv4NativeRoutingCIDR: "10.244.0.0/16"
            ipam:
              mode: "kubernetes"
            bpf:
              masquerade: true
              tproxy: true
            hubble:
              enabled: true
              relay:
                enabled: true
              ui:
                enabled: true
            operator:
              replicas: 3
  konnectivity:
    adminPort: 8133
    agentPort: 8132
  network:
    clusterDomain: cluster.local
    dualStack:
      enabled: false
    kubeProxy:
      disabled: true
    kuberouter:
      enabled: false
    podCIDR: 10.244.0.0/16
    serviceCIDR: 10.96.0.0/12
    provider: custom
  storage:
    type: etcd
    etcd:
      ca:
        expiresAfter: 87600h
        certificatesExpireAfter: 8760h
  telemetry:
    enabled: true
