apiVersion: v1
kind: Secret
metadata:
  name: harbor-secrets
  namespace: harbor
type: Opaque
stringData:
  # S3 (Harbor registry storage) - Harbor chart expects these exact keys
  REGISTRY_STORAGE_S3_ACCESSKEY: SZ3E4FYUF5F0MPTP2ZZO
  REGISTRY_STORAGE_S3_SECRETKEY: b6xCHGjj8bHBAr475kBvOqbNercPLLqnh8plXSfj

  # Internal database (PostgreSQL) password
  POSTGRESQL_PASSWORD: L4dmsxF5Wp4nddXMRDEdLt1P

  # Internal redis password (optional but recommended)
  REDIS_PASSWORD: krhapcdmZ9A1iia9xgzoTeLD

  # Harbor admin password (optional but recommended)
  HARBOR_ADMIN_PASSWORD: wUyqEtP5kaachseBMwiXoDyr
