# yaml-language-server: $schema=https://raw.githubusercontent.com/KevinNitroG/argocd-json-schema/refs/heads/main/schemas/v3.2.2/standalone-strict/v1alpha1appproject.json
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ayame-apps
spec:
  sourceRepos:
    - "https://github.com/AsnkOSS/ayame-cluster"
  destinations:
    - name: "ayame-cluster"
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/KevinNitroG/argocd-json-schema/refs/heads/main/schemas/v3.2.2/standalone-strict/v1alpha1applicationset.json
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ayame-apps
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/AsnkOSS/ayame-cluster.git
        revision: main
        directories:
          - path: platform/apps/*
  template:
    metadata:
      name: "{{ .path.basename }}"
    spec:
      project: ayame-apps
      source:
        repoURL: https://github.com/AsnkOSS/ayame-cluster.git
        targetRevision: main
        path: "{{ .path.path }}"
      destination:
        name: "mimosa"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
