apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: matrix-mautrix-telegram
  namespace: matrix
spec:
  replicas: 1
  podManagementPolicy: OrderedReady
  revisionHistoryLimit: 0
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      app: matrix-mautrix-telegram
  template:
    metadata:
      labels:
        app: matrix-mautrix-telegram
    spec:
      securityContext:
        fsGroup: 1000

      initContainers:
      containers:
        - name: matrix-mautrix-telegram
          image: dock.mau.dev/mautrix/telegram:latest
          volumeMounts:
            - name: matrix-mautrix-telegram-data
              mountPath: /data

      volumes:
        - name: matrix-mautrix-telegram-data
          persistentVolumeClaim:
            claimName: matrix-mautrix-telegram-data
