apiVersion: v1
kind: Service
metadata:
  name: matrix-mautrix-telegram-service
  namespace: matrix
spec:
  selector:
    app: matrix-mautrix-telegram
  ports:
    - name: http
      port: 29317
      targetPort: 29317
  type: ClusterIP
