apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bluesky-cert
  namespace: istio-ingress
spec:
  secretName: bluesky-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  dnsNames:
    - "bsky.sne.moe"
    - "*.bsky.sne.moe"
