apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ztunnel
  namespace: istio-system
spec:
  template:
    spec:
      containers:
        - args:
            - proxy
            - ztunnel
          env:
            - name: CA_ADDRESS
              value: istiod.istio-system.svc:15012
            - name: XDS_ADDRESS
              value: istiod.istio-system.svc:15012
            - name: RUST_LOG
              value: info
            - name: RUST_BACKTRACE
              value: "1"
            - name: ISTIO_META_CLUSTER_ID
              value: Kubernetes
            - name: INPOD_ENABLED
              value: "true"
            - name: TERMINATION_GRACE_PERIOD_SECONDS
              value: "30"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: INSTANCE_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.serviceAccountName
            - name: ZTUNNEL_CPU_LIMIT
              valueFrom:
                resourceFieldRef:
                  divisor: "0"
                  resource: limits.cpu
          image: docker.io/istio/ztunnel:1.28.2
          imagePullPolicy: IfNotPresent
          name: istio-proxy
          ports:
            - containerPort: 15020
              name: ztunnel-stats
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz/ready
              port: 15021
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - NET_ADMIN
                - SYS_ADMIN
                - NET_RAW
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1337
            runAsNonRoot: false
            runAsUser: 0
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/run/secrets/istio
              name: istiod-ca-cert
            - mountPath: /var/run/secrets/tokens
              name: istio-token
            - mountPath: /var/run/ztunnel
              name: cni-ztunnel-sock-dir
            - mountPath: /tmp
              name: tmp
