apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: ztunnel
    namespace: istio-system

spec:
    template:
        spec:
            containers:
                env:
                    - name: ZTUNNEL_CPU_LIMIT
                      valueFrom:
                          resourceFieldRef:
                              divisor: "0"
                              resource: limits.cpu
