apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: harbor-nginx
  namespace: harbor
spec:
  host: harbor-nginx.harbor
  trafficPolicy:
    tls:
      mode: DISABLE

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: harbor-redis
  namespace: harbor
spec:
  host: harbor-redis.harbor
  trafficPolicy:
    tls:
      mode: DISABLE

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: harbor-database
  namespace: harbor
spec:
  host: harbor-database.harbor
  trafficPolicy:
    tls:
      mode: DISABLE

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: harbor-trivy
  namespace: harbor
spec:
  host: harbor-trivy.harbor
  trafficPolicy:
    tls:
      mode: DISABLE

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: hetzner-objectstorage
  namespace: harbor
spec:
  host: fsn1.your-objectstorage.com
  trafficPolicy:
    tls:
      mode: SIMPLE
      sni: fsn1.your-objectstorage.com
