apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: harbor
  namespace: harbor
spec:
  host: harbor.harbor.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: harbor-core
  namespace: harbor
spec:
  host: harbor-core.harbor.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: harbor-database
  namespace: harbor
spec:
  host: harbor-database.harbor.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: harbor-jobservice
  namespace: harbor
spec:
  host: harbor-jobservice.harbor.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: harbor-portal
  namespace: harbor
spec:
  host: harbor-portal.harbor.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: harbor-registry
  namespace: harbor
spec:
  host: harbor-registry.harbor.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: harbor-trivy
  namespace: harbor
spec:
  host: harbor-trivy.harbor.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: hetzner-objectstorage
  namespace: harbor
spec:
  host: fsn1.your-objectstorage.com
  trafficPolicy:
    tls:
      mode: SIMPLE
      sni: fsn1.your-objectstorage.com
