apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: harbor-redis-plain
  namespace: harbor
spec:
  host: harbor-redis.harbor.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: hetzner-s3
  namespace: harbor
spec:
  host: fsn1.your-objectstorage.com
  trafficPolicy:
    tls:
      mode: SIMPLE
      sni: fsn1.your-objectstorage.com
