apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: hetzner-object-storage
  namespace: harbor
spec:
  hosts:
    - fsn1.your-objectstorage.com
  ports:
    - number: 443
      name: https
      protocol: HTTPS
  location: MESH_EXTERNAL
  resolution: DNS
