apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: harbor
  namespace: harbor
spec:
  hosts:
    - registry.asnk.io
  gateways:
    - harbor-gateway
  http:
    - match:
        - port: 80
      redirect:
        scheme: https
        redirectCode: 308

    - match:
        - port: 443
      route:
        - destination:
            host: harbor.harbor.svc.cluster.local
            port:
              number: 80
