apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: harbor
  namespace: harbor
spec:
  hosts:
    - harbor-nginx.ayame.asnk.io
  gateways:
    - istio-system/harbor-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: harbor.harbor.svc.cluster.local
            port:
              number: 80
