apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitea-meilisearch
  namespace: gitea
spec:
  serviceName: gitea-meilisearch
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: gitea-meilisearch
  template:
    metadata:
      labels:
        app: gitea-meilisearch
    spec:
      containers:
        - name: gitea-meilisearch
          image: getmeili/meilisearch:v1.32
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7700
              name: http
          env:
            - name: MEILI_ENV
              value: "production"
            - name: MEILI_NO_ANALYTICS
              value: "true"
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: gitea-secrets
                  key: MEILI_MASTER_KEY
          volumeMounts:
            - name: meili-data
              mountPath: /meili_data
          readinessProbe:
            httpGet:
              path: /health
              port: 7700
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 7700
            initialDelaySeconds: 30
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: meili-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: hcloud-volumes
        resources:
          requests:
            storage: 10Gi
