apiVersion: v1
kind: Service
metadata:
  name: gitea-postgres
  namespace: gitea
spec:
  selector:
    app: gitea-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
