---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    token: AgDGmFrnj2SzsAdBhNc/PTb/2yM7a4h98iLjwoQ2HqxyDXiR1Re/xHDq0i5veMyACWDoAtcsM0hsJidhL0oKZcuePWJs00dgG7sC+y0e0eEcsNfO5y4cDAC1s/7fTPShz5dKpDB/SL1j7JLJ0hLqdrOc4xh6aqipVOhtgtZs5W86CqN6EpR72FKzMhxpZv9oW0fFmP2W/cuPl5AjtmE6L2Qe80LsVOmprYVlySROWB2CkAsMnwljGCp4TqLJINkgy38uUXu+hd/JT6delWvhfukdlZ/2Pov1dNFmeaVqdWFzHQQ5LyeqnnMKdHGFhHUz63VX52XjpAFQwvMGUyhhFQ+f5vIqaj+FJjokFnhD9dFB2iDeUPjPyzz6Jet4R49qLtTvxpaRgM66hyTZQ+ilAaGlLNkHyHwalGTsv3VgHVgojbmbY45wKminzM3w+vh9TDlO2CpvR4Bbo+robtdjbb5EVfGFIW/Bqw7hv3wizEa9Zak+M1mL8jqA6X2tf/9uCvkk40EEG/QSJS0IZpaVr86XGbb1wn8C2mTy7pQDXRC+0MBNfonHclZGavqF0nncgThuETrkLWqh+CJ0dxQyHJw8axVoxjgU50Icm9J5HPRwZ3IO5/A8W3TRJ+a7izXlA8A9QQ01tT9crkKXMP6TzZXei2Xk0OLM1OWvqo8Sjrero43Mz4ya8U/u457MxrQG1OLNeCxseZrrmi4VlYiuZN1N+d203YFnG4K2c3qWULGivHByNRaelSff
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
