---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: samba-csi-secrets
  namespace: samba-csi
spec:
  encryptedData:
    password: AgBnNOquuTOEyuOEmXPWlImp/2ImE8CFroFqj8i/H2pib7BRkj3npITIny8mBU7JPh1sH/BKFnJCe0hOHPO3dqwXmO0cemrci4VROCh2p3FHr/gxFGEl9+CG4zazfce6Rr8RzgxWK1bNKlJQCHi3DtzBuht9JvEOExahDQkOoKCZmf1CfHp3zxpNnZNpIJu0HuMDkaCuu3RuD3nmiPcVnhlN+YNBEiTRAAslG7Hkd1UySlh70FBaZ4E5ZjI46/i/9GFEsQWSnt1US08QP+JelNVTfjoB16a4QL0tT6+9mtOIJafaqZC6jfFFCEW8Wk6ko5fMKVHXKDOoDiYH0F5oJKUDDZc2ElAWek/re0qJxvPbYpIcMolRroo5DznO9Tik7hKerEyZQe6nh7ba1bZ8Pn5ErFQlemL6jB4EKtlG8YkCFdixRR+zmHf7J8LFV9ByF72+T6c7Rpt7i9eeTdyyMviZbkJQpdTnRZlYNiCsJhH03+QvXaDI1TYNGZ18EP2zy9mwv4QzRxEIJN4FR7qXiFPSteoUxAbugGhOcFkinTZc1oeKY2DdISXoQfNznSoHyAfTDbjF/7dTGol/x8R0xbVSc1xsGtDA0Cw2aeY+9bm1zHo0mn1u6eulnCB10ZkB3Nof8U7tY+o2R79NmkhDdCCo+iK4cSaG3aLR1wf6q7VTWhKUpUx63IYZqJ3rce9Wjj6zKeYBFRc8pS9ClQulSq2/JXZKbnt6Pvo=
    username: AgDFROIqFh/rYYLOFPL4E6xIANH90s3cnrOe4csj6S7MNf2XkDQ+8XDYn/FtGQTMo7hiLRTlKKLNs5aUbfepT9twSXA34EvMhDOXRNwDdM95cjcqahY7iYmNs/obIzItZafkxvFB/QziFZO13L4s5ZuELLOrIZuwfJCj+ZVf35NzgJn1q5LSAET95h+Ec+xZutPf6B3sp+V6upxychBCACL67ZqGrOZ0xH7Ysy5r5rnK/bTQaGGty7DujdG/NAJaqf7sTdX5eFHT2yvR52dauaGMeYcgIzkwefE+RcMJ7Di9HK3ykIXTBivw6xpbQpOy+EZuDR4oN4c1seFCkg8F0R6W5akQYGofqQ7FPzKqhVYv8UPomoxHUz8cyXcGU+RFsGM3PZo5hoSyP47tNfaf5Rsh1f32yjKnZz3zxN90+XXHz5qJ+Ta2TMvhqLhkeGCRqtQI22t3EETETQo7MxtR9wS/lPuVSXZd6JvkfdnO2B9o+VcC1FSewbbtGTdt8SidjuwY2OG8jBqONtH3tHPwwVyNv76dJX69J6BJVxK0rzTHa8RtaNQiPXT2QC5i1HQ7PjH2qxAbY1w8K7LxG9JXG7HIxdiMDNkpClamFi+wi4/4wqLSPzeomnP3eFKvYFPhA2N9Oqq6WKfCbWkfXVFyEZFgFzoFOEiYDww+H8B2vdCO8M3WDscv2X+CpGgSIGyjIZaRKUde+IrM
  template:
    metadata:
      name: samba-csi-secrets
      namespace: samba-csi
