apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: uptime-kuma-cert
  namespace: istio-ingress
spec:
  secretName: uptime-kuma-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  dnsNames:
    - status.asnk.io
