apiVersion: v1
kind: Service
metadata:
  name: nixcn-cms-prod-redis-service
  namespace: nixcn-cms-prod
spec:
  selector:
    app: nixcn-cms-prod-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  type: ClusterIP
