apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitea-redis
  namespace: gitea
spec:
  serviceName: gitea-redis-service
  replicas: 1
  podManagementPolicy: OrderedReady
  revisionHistoryLimit: 0
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      app: gitea-redis
  template:
    metadata:
      labels:
        app: gitea-redis
    spec:
      containers:
        - name: redis
          image: redis:8-alpine
          ports:
            - containerPort: 6379
              name: redis
          args:
            - "redis-server"
            - "--save"
            - ""
            - "--appendonly"
            - "no"
            - "--stop-writes-on-bgsave-error"
            - "no"
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 20
            periodSeconds: 10
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
