---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hcloud
  namespace: kube-system
spec:
  encryptedData:
    token: AgAVfR/IBVDm6XXmMZZJNfdSdLWzondbx/NF26N1BTUae9K4C6P3bEQtZLe6y9uHVTR6NwVErgcbcPcj4BVNywURMmCWMIOk5BOB0SJEgxLl58SoVsw4ISLqwgzxt8vkWFJqgf/XEuX3q7ZY9fp9oYGbbOUUeQ0fraKXmYEkOu0tE9poOP5ZFJ8iSM2LgDcq6+rSiSL2RFrF1qcRPHyxcmxu8w42tbernWA68cicenSjIMuIKmcBni/fAnlVTNIKgA0jTA0gIeSaEmfFRNqzQ7uQpTPsMWRI1so0o++7df2ZHtPRaSZfuX4kSU8zoBVoGFnmpe+paJfUwgYk9/gYlw7uGChRSz2J2E87OMc62S3lFXM+dsV+GPMrQoLKUxB92fQjQ9wobcM5tBruD9tpYhaBm1Lc7VcqkwMRHY+b7O6lnen+jTP0+Jc2YhcTbgFEvxkXomdklfX9T/hKhv3OyIv+rZnUP8SNmFc4yRBp2gTTTHsXIwbnQPig0qyG65GXQiQa84XDgYIICup/1HwS04A+2xdGcWYLyvzVuTS6akYmS7ioQwGoCr+5ESXLatLYs+SmtBWww5ZsBIvxBA9DWGDduR1QIkXRJ0B/taTjDkt70kiwTYnwTHrSvvDpBhJSX9PB9sLD1G4mAuKCeQtzla8mNtpaj2BHLgZq3ESiZ37th0okPVG4W3A0aP5tiXmfQGw3YqXlEOhExI8pDGOXzP0hsXQNVkwO95Wql3XmwxIznqw1KsS4NEvVreaTM9I97MK9rJw1JD1XnGvXTTSkmeHk
  template:
    metadata:
      name: hcloud
      namespace: kube-system
