---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hcloud
  namespace: kube-system
spec:
  encryptedData:
    token: AgBomD0wD0VlXeZglmqsnHMBDVj/DcKFOc86FLy/J5HPoYpGm66lp25G+tmGpVkrZOeAe5o2IH16BkV0fMxRcjzl8+yhgFTbR1y6cyHxrsxurmo4vBc0MLjr13SRZkX14O/jHMsZ7rYC/CVryaGsfHr+WGSyVnZQ3/A2SKOboAfkLuUBptDOJ0527aAcLlnbhf47lLCW6kEI6B6huINRiFAXfIF2yPYnyIYy8WXCPNFoi17JWjY076dou+k5z3Mq8v6pjtOpufIBYMSzS33gXRS2GEENRazAX31xq9SI4iptyCsBx7sEfyYYNIEYMWSR0mVWb/UQrugk4y0fhE0gvZ7Fkhz0N/q/WZ2oDBCmuBR5jNC7rexBDBXd1HRFsl4289AFbeiP9iZXtc+4qro7X8Vu8jXETXjHVc3JSGlVJi3vO1wo8r7eXhLPhfOPEuC05JJsaCGSCVrb4UaUSbO2n/MyLfygRzVI+4xLuBW9oKVlR9Hiqqd1ZdferO1E+xd79p7F7n+2+zuRPcAY24T3zDRBgyFIKCU2WqVx8BGrYEZAuUOtW8vXjsOEll/peS845ZVNk/+iR0v3dgNpMkGprZa6sDUrSfe5MGY83acPuhSHtfg3BoO2dfna+7huUTiqP5hd4ng4jSMMNs2hQHq/wOiqtWbE47hmZodlafaTkf2LphBxvrMFIVTnELGMYkSe9TTPQbqKXPTo+cSv8E3X2OTm2OHk/VBm/5OH00L04MIreL6DvQMEtpMM1e6toNJgCJyQrXj23asZ99cPV5LA845z
  template:
    metadata:
      name: hcloud
      namespace: kube-system
