apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamcity-server-data
  namespace: teamcity
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: smb
  resources:
    requests:
      storage: 300Gi
