apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamcity-server-logs
  namespace: teamcity
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: hcloud-volumes
  resources:
    requests:
      storage: 10Gi
