apiVersion: v1
kind: Service
metadata:
  name: teamcity-server-service
  namespace: teamcity
spec:
  selector:
    app: teamcity-server
  ports:
    - name: http
      port: 8111
      targetPort: 8111
  type: ClusterIP
