apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: teamcity-postgres
  namespace: teamcity
spec:
  serviceName: teamcity-postgres-service
  replicas: 1
  podManagementPolicy: OrderedReady
  revisionHistoryLimit: 0
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      app: teamcity-postgres
  template:
    metadata:
      labels:
        app: teamcity-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14-alpine
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: teamcity
            - name: POSTGRES_USER
              value: teamcity
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: teamcity-secrets
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: "/data/pgdata"
          volumeMounts:
            - name: pgdata
              mountPath: /data
          readinessProbe:
            exec:
              command:
                ["sh", "-c", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                ["sh", "-c", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: teamcity-postgres-data
