---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nixcn-cms-test-registry-key
  namespace: nixcn-cms-test
spec:
  encryptedData:
    .dockerconfigjson: AgCHUBKrx+vgc9h/ZoM73fjzHLNALb01Iceqtsa1yd5puNZV9CBHxJWmCVbVe9CqYEccHT1zjzQHxJ8EKctIivQfjjVgLbZthyiCdifKAZaPTqFEMTcqRZCUjn4ckbWDNZPfJ6QCpUTRIeYjY2JQ1zIjgxR2CBEXhnOmJWq7hLN0d3GN6KQ72EyID8zAdrmnJoxY1SKD8yaQ6plcahyfN/m66nN1UMRFJWhFxej3RZnl+Qt3BwlIUm/7dyooEazxuxTQZDkeSqUUo2a9LSmlG6xEQXAJ6HScU2POLFwsyNHvtKk4iwZaLE3nZDkyzwAxyPvrob/kp6pAIZcJolVlgYaN0KxpafDxWG5qE6W4o3XfMeSLawp9Aq92pY5lWpcyCk8gvFpw8rAWy6U5UbOLdRKNNY1K4oILHaJHWVl5SR3OWYfiztAsOAaRpB0SLNKmIymdKMXROMmbOGrVV7k2292vuZPoeWGXKJEoitolBnwpWQc7G9XTsbAEmOsuomedPRwZrpogYp5gyO95r/hhjqKfkkqxesQcIB3Ieda0swRuqWl2gnTfFhouinwQjdtQBHAEliU/c0Viwg04kgd7y7Uvilyz+at0kEfE9WKducvzm9ilAOcLsNm22DX17d7AGHk+pJEsaSUzinA27cLCklqdCoC4xFZvm5xIBy4oKKTRehznYYztQdtJEc25nJfyK+7NcM//+jJ+yJ20Y7x3HptZWQbyDbwqNWVH4G61n2bttxl4Ydu0q2Gda24laI0p9ZqFGBw2ADzSKe0p77XK8f+OY5svxGQuAQVaVK07uL3jtzzNBUBJMofyg0w4GL1zrGbPM20GLGHoQiBF+pcf53mvsaoKvXEOtsMTeHDVGk3xRCqcrLSBHWk2LScBvJnc4OPHR+Ms/HNqbFaEYzmM7XcGW7ARLNH1Ye47uEcbKpO2U4zLGM/UlLEXKydYY+ztfz0WMw==
  template:
    metadata:
      name: nixcn-cms-test-registry-key
      namespace: nixcn-cms-test
    type: kubernetes.io/dockerconfigjson
