apiVersion: v1
kind: Service
metadata:
  name: matrix-synapse-service
  namespace: matrix
spec:
  selector:
    app: matrix-synapse
  ports:
    - name: http
      port: 8008
      targetPort: 8008
  type: ClusterIP
