apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
    name: ayame-cluster
    user: admin

spec:
    k0s:
        version: v1.34.3+k0s.0
        config:
            apiVersion: k0s.k0sproject.io/v1beta1
            kind: ClusterConfig
            metadata:
                name: ayame-cluster
            spec:
                api:
                    externalAddress: 10.0.0.2
                    port: 6443
                    k0sApiPort: 9443
                    sans:
                        - 10.0.0.2
                        - 128.140.29.78
                    ca:
                        expiresAfter: 87600h
                        certificatesExpireAfter: 8760h

                controllerManager: {}

                extensions:
                    helm:
                        concurrencyLevel: 5

                installConfig:
                    users:
                        etcdUser: etcd
                        kineUser: kube-apiserver
                        konnectivityUser: konnectivity-server
                        kubeAPIserverUser: kube-apiserver
                        kubeSchedulerUser: kube-scheduler

                konnectivity:
                    adminPort: 8133
                    agentPort: 8132

                network:
                    clusterDomain: ayame-cluster.local
                    dualStack:
                        enabled: true
                        IPv6podCIDR: fd00:10:244::/108
                        IPv6serviceCIDR: fd00:10:96::/108
                    kubeProxy:
                        iptables:
                            minSyncPeriod: 0s
                            syncPeriod: 0s
                        ipvs:
                            minSyncPeriod: 0s
                            syncPeriod: 0s
                            tcpFinTimeout: 0s
                            tcpTimeout: 0s
                            udpTimeout: 0s
                        metricsBindAddress: 0.0.0.0:10249
                        mode: iptables
                    calico:
                        mode: bird
                    nodeLocalLoadBalancing:
                        enabled: false
                    provider: calico
                    podCIDR: 10.244.0.0/16
                    serviceCIDR: 10.96.0.0/12

                scheduler: {}

                storage:
                    type: etcd
                    etcd:
                        ca:
                            expiresAfter: 87600h
                            certificatesExpireAfter: 8760h

                telemetry:
                    enabled: true

    hosts:
        # Master 1
        - ssh:
              address: 5.75.252.128
              user: root
              port: 22
              keyPath: ./secrets/ayame-cluster.key
          role: controller+worker
          privateAddress: 10.0.0.11
          noTaints: true
          installFlags:
              - --kubelet-extra-args="--node-ip=10.0.0.11"

        # Master 2
        - ssh:
              address: 46.224.107.21
              user: root
              port: 22
              keyPath: ./secrets/ayame-cluster.key
          role: controller+worker
          privateAddress: 10.0.0.12
          noTaints: true
          installFlags:
              - --kubelet-extra-args="--node-ip=10.0.0.12"

        # Master 3
        - ssh:
              address: 49.13.208.38
              user: root
              port: 22
              keyPath: ./secrets/ayame-cluster.key
          role: controller+worker
          privateAddress: 10.0.0.13
          noTaints: true
          installFlags:
              - --kubelet-extra-args="--node-ip=10.0.0.13"

        # Node 1
        - ssh:
              address: 128.140.56.33
              user: root
              port: 22
              keyPath: ./secrets/ayame-cluster.key
          role: worker
          privateAddress: 10.0.0.21
          installFlags:
              - --kubelet-extra-args="--node-ip=10.0.0.21"

        # Node 2
        - ssh:
              address: 46.224.98.2
              user: root
              port: 22
              keyPath: ./secrets/ayame-cluster.key
          role: worker
          privateAddress: 10.0.0.22
          installFlags:
              - --kubelet-extra-args="--node-ip=10.0.0.22"

        # Node 3
        - ssh:
              address: 91.98.33.230
              user: root
              port: 22
              keyPath: ./secrets/ayame-cluster.key
          role: worker
          privateAddress: 10.0.0.23
          installFlags:
              - --kubelet-extra-args="--node-ip=10.0.0.23"
