apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ztunnel
  namespace: istio-system
spec:
  revisionHistoryLimit: 10
  template:
    spec:
      containers:
        - env:
            - name: ZTUNNEL_CPU_LIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
