apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ztunnel
  namespace: istio-system
spec:
  revisionHistoryLimit: 10
  template:
    spec:
      containers:
        - args:
            - proxy
            - ztunnel
          env:
            - name: CA_ADDRESS
              value: istiod.istio-system.svc:15012
            - name: XDS_ADDRESS
              value: istiod.istio-system.svc:15012
            - name: RUST_LOG
              value: info
            - name: RUST_BACKTRACE
              value: "1"
            - name: ISTIO_META_CLUSTER_ID
              value: Kubernetes
            - name: INPOD_ENABLED
              value: "true"
            - name: TERMINATION_GRACE_PERIOD_SECONDS
              value: "30"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: INSTANCE_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.serviceAccountName
            - name: ISTIO_META_ENABLE_HBONE
              value: "true"
            - name: ZTUNNEL_CPU_LIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
