apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ztunnel
  namespace: istio-system
spec:
  revisionHistoryLimit: 10
  template:
    spec:
      containers:
        - name: ztunnel

          env:
            - name: ISTIO_META_ENABLE_HBONE
              value: "true"
            - name: ZTUNNEL_CPU_LIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
