apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: matrix-synapse-postgres
  namespace: matrix
spec:
  serviceName: matrix-synapse-postgres-service
  replicas: 1
  podManagementPolicy: OrderedReady
  revisionHistoryLimit: 0
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      app: matrix-synapse-postgres
  template:
    metadata:
      labels:
        app: matrix-synapse-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:18.1-bookworm
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: matrix_synapse
            - name: POSTGRES_USER
              value: matrix_synapse
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: matrix-secrets
                  key: MATRIX_SYNAPSE_POSTGRES_PASSWORD
            - name: PGDATA
              value: "/data/pgdata"
            - name: POSTGRES_INITDB_ARGS
              value: "--lc-collate=C --lc-ctype=C"
          volumeMounts:
            - name: pgdata
              mountPath: /data
          readinessProbe:
            exec:
              command:
                ["sh", "-c", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                ["sh", "-c", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: matrix-synapse-postgres-data
