apiVersion: v1
kind: Service
metadata:
  name: matrix-synapse-postgres-service
  namespace: matrix
spec:
  selector:
    app: matrix-synapse
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
