apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitea-cnpg
  namespace: gitea
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:14
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: hcloud-volumes
      volumeMode: Filesystem
