apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitea-cnpg
  namespace: gitea
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:14
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: hcloud-volumes
      volumeMode: Filesystem

  bootstrap:
    pg_basebackup:
      source: source-db

  externalClusters:
    - name: source-db
      connectionParameters:
        host: gitea-postgres.gitea
        user: streaming_replica
        dbname: gitea
        sslmode: disable
      password:
        name: source-db-replica-user
        key: password
