apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pds-data
  namespace: bluesky
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: hcloud-volumes
  resources:
    requests:
      storage: 20Gi
