apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nixcn-cms-test-redis-data
  namespace: nixcn-cms-test
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: hcloud-volumes
  resources:
    requests:
      storage: 10Gi
