apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nixcn-cms-test-redis
  namespace: nixcn-cms-test
spec:
  serviceName: nixcn-cms-test-redis-service
  replicas: 1
  podManagementPolicy: OrderedReady
  revisionHistoryLimit: 0
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      app: nixcn-cms-test-redis
  template:
    metadata:
      labels:
        app: nixcn-cms-test-redis
    spec:
      securityContext:
        fsGroup: 1000

      initContainers:
        - name: init-redis-dir
          image: alpine:3.19
          command: ["sh", "-c"]
          args:
            - |
              set -eu
              mkdir -p /data/redis
              chown -R 1000:1000 /data/redis
              chmod -R g+rwX /data/redis
          volumeMounts:
            - name: redisdata
              mountPath: /data

      containers:
        - name: redis
          image: redis:8-alpine
          ports:
            - containerPort: 6379
              name: redis
          args:
            - "redis-server"
            - name: redisdata
              mountPath: /data
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 20
            periodSeconds: 10
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000

      volumes:
        - name: redisdata
          persistentVolumeClaim:
            claimName: nixcn-cms-test-redis-data
