apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-jobservice
  namespace: harbor
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
