apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pocketid-data
  namespace: pocketid
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: hcloud-volumes
  resources:
    requests:
      storage: 10Gi
