apiVersion: v1
kind: Service
metadata:
  name: pocketid-service
  namespace: pocketid
spec:
  selector:
    app: pocketid
  ports:
    - name: http
      port: 1411
      targetPort: 1411
  type: NodePort
