apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitea
  namespace: gitea
spec:
  serviceName: gitea-service
  replicas: 1
  podManagementPolicy: OrderedReady
  revisionHistoryLimit: 0
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      securityContext:
        fsGroup: 1000

      initContainers:
        - name: init-dirs
          image: alpine:3.23
          command: ["sh", "-c"]
          args:
            - |
              set -eu
              mkdir -p /data/gitea
              chown -R 1000:1000 /data/gitea
          volumeMounts:
            - name: gitea-data
              mountPath: /data
            - name: appini
              mountPath: /in
              readOnly: true

        - name: render-appini
          image: alpine:3.23
          command: ["sh", "-c"]
          args:
            - |
              set -eu
              apk add --no-cache gettext
              envsubst < /in/app.ini > /data/app.ini
              chown 1000:1000 /data/app.ini
              chmod 600 /data/app.ini
          env:
            - name: GITEA_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gitea-secrets
                  key: GITEA_DATABASE_PASSWORD
            - name: GITEA_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: gitea-secrets
                  key: GITEA_SECRET_KEY
            - name: GITEA_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: gitea-secrets
                  key: GITEA_JWT_SECRET
            - name: GITEA_EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gitea-secrets
                  key: GITEA_EMAIL_PASSWORD
            - name: HCAPTCHA_SECRET
              valueFrom:
                secretKeyRef:
                  name: gitea-secrets
                  key: HCAPTCHA_SECRET
            - name: HCAPTCHA_SITEKEY
              valueFrom:
                secretKeyRef:
                  name: gitea-secrets
                  key: HCAPTCHA_SITEKEY
            - name: METRICS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gitea-secrets
                  key: METRICS_TOKEN
            - name: MINIO_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: gitea-secrets
                  key: MINIO_ACCESS_KEY_ID
            - name: MINIO_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: gitea-secrets
                  key: MINIO_SECRET_ACCESS_KEY
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: gitea-secrets
                  key: MEILI_MASTER_KEY
          volumeMounts:
            - name: gitea-data
              mountPath: /data
            - name: appini
              mountPath: /in
              readOnly: true

      containers:
        - name: gitea
          image: docker.gitea.com/gitea:1.25.3-rootless
          ports:
            - containerPort: 3000
              name: http
            - containerPort: 2222
              name: tcp-ssh
          args:
            - gitea
            - web
            - --work-path
            - /data/gitea
            - --custom-path
            - /data/gitea
            - --config
            - /data/app.ini
          env:
            - name: USER_UID
              value: "1000"
            - name: USER_GID
              value: "1000"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gitea-secrets
                  key: DATABASE_PASSWORD
          volumeMounts:
            - name: gitea-data
              mountPath: /data

          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10

      volumes:
        - name: gitea-data
          persistentVolumeClaim:
            claimName: gitea-data
        - name: appini
          secret:
            secretName: gitea-appini
            items:
              - key: app.ini
                path: app.ini
